import { TourStep } from './PageTour';

export const settingsTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: null,
    title: 'Welcome to Settings! ⚙️',
    content: 'This is where you can manage your account, billing, security, and preferences. Let\'s walk through each section!',
    position: 'center',
    spotlightPadding: 0,
  },
  {
    id: 'profile-display',
    target: '[data-tour="settings-profile-display"]',
    title: 'Profile Display',
    content: 'Choose how you want to appear across Clemelopy. Upload a photo or display your initials - the choice is yours!',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'profile-info',
    target: '[data-tour="settings-profile-info"]',
    title: 'Profile Information',
    content: 'View and edit your personal and business details. Click "Edit" to update your name, phone, address, company info, and website.',
    position: 'left',
    spotlightPadding: 12,
  },
  {
    id: 'billing',
    target: '[data-tour="settings-billing"]',
    title: 'Billing & Subscription',
    content: 'See your current plan. Click "Manage Subscription" to upgrade, downgrade, or update payment methods through our secure Stripe portal.',
    position: 'top',
    spotlightPadding: 12,
  },
  {
    id: 'transactions',
    target: '[data-tour="settings-transactions"]',
    title: 'Transaction History',
    content: 'View all your past invoices and payments. You can download PDF receipts for your records or accounting.',
    position: 'top',
    spotlightPadding: 12,
  },
  {
    id: 'security',
    target: '[data-tour="settings-security"]',
    title: 'Security Settings',
    content: 'Keep your account safe! Change your password anytime, and enable Two-Factor Authentication (2FA) for extra protection using apps like Google Authenticator or Authy.',
    position: 'top',
    spotlightPadding: 12,
  },
  {
    id: 'preferences',
    target: '[data-tour="settings-preferences"]',
    title: 'Preferences',
    content: 'Customize your Clemelopy experience. Choose your sidebar behavior (collapsed, expand on hover, or always expanded) and restart the workspace tour anytime from here.',
    position: 'top',
    spotlightPadding: 12,
  },
  {
    id: 'deleted-items',
    target: '[data-tour="settings-deleted-items"]',
    title: 'Recently Deleted',
    content: 'Accidentally deleted something? No worries! Recover deleted to-dos and linking strategy projects within 14 days. After that, they\'re permanently removed.',
    position: 'top',
    spotlightPadding: 12,
  },
  {
    id: 'danger-zone',
    target: '[data-tour="settings-danger-zone"]',
    title: 'Danger Zone',
    content: 'This is where you can permanently delete your account if needed. Be careful - this action cannot be undone and all your data will be lost forever.',
    position: 'top',
    spotlightPadding: 12,
  },
];
