import { TourStep } from './PageTour';

export const shareOfModelTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: null,
    title: 'Welcome to Share of Model! 📊',
    content: 'Track how often AI platforms like ChatGPT, Perplexity, Claude, and Gemini mention your brand compared to competitors. Let\'s explore!',
    position: 'center',
    spotlightPadding: 0,
  },
  {
    id: 'dashboard-tab',
    target: '[data-tour="som-tab-dashboard"]',
    title: 'Dashboard',
    content: 'Your command center! See your overall Share of Voice, visibility metrics, and how you compare against competitors at a glance.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'metrics-cards',
    target: '[data-tour="som-metrics-cards"]',
    title: 'Key Metrics',
    content: 'These cards show your Share of Voice, Average Position, Sentiment Score, and Citation Rate. Hover over the ⓘ icons for explanations of each metric.',
    position: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'share-of-voice',
    target: '[data-tour="som-share-of-voice"]',
    title: 'Share of Voice Comparison',
    content: 'See how your brand stacks up against competitors. Click any bar to view detailed mentions and responses where that brand appeared.',
    position: 'right',
    spotlightPadding: 12,
  },
  {
    id: 'platform-breakdown',
    target: '[data-tour="som-platform-breakdown"]',
    title: 'Platform Breakdown',
    content: 'Your visibility varies by platform! Click any platform card to see all the responses from that AI and where you were mentioned.',
    position: 'top',
    spotlightPadding: 12,
  },
  {
    id: 'manual-test-tab',
    target: '[data-tour="som-tab-manual"]',
    title: 'Manual Test',
    content: 'Test a single query on one platform at a time. Great for quick spot-checks or testing specific questions about your brand.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'automated-test-tab',
    target: '[data-tour="som-tab-automated"]',
    title: 'Automated Test',
    content: 'Run multiple queries across 4 AI platforms at once! This is the fastest way to gather comprehensive data about your brand visibility.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'competitors-tab',
    target: '[data-tour="som-tab-competitors"]',
    title: 'Competitors',
    content: 'Add your brand (marked with ⭐) and competitors you want to track. The AI will detect when any of these are mentioned in responses.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'queries-tab',
    target: '[data-tour="som-tab-queries"]',
    title: 'Queries',
    content: 'Create the questions you want to test. Think about what your potential customers might ask AI platforms when looking for solutions like yours.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'history-tab',
    target: '[data-tour="som-tab-history"]',
    title: 'History',
    content: 'View all your past tests organized by session. Expand any session to see the full AI responses and which brands were mentioned.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'research-tab',
    target: '[data-tour="som-tab-research"]',
    title: 'Research Notes',
    content: 'Ask AI platforms custom questions about your business and save the insights for later. Great for competitive research and content planning!',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'complete',
    target: null,
    title: 'You\'re All Set! 🎉',
    content: 'Start by adding your brand in Competitors, create some test queries, then run an Automated Test to see where you stand. After tests complete, you\'ll see discovered brands and content recommendations. Good luck!',
    position: 'center',
    spotlightPadding: 0,
  },
];