import { TourStep } from './PageTour';

export const todoTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: null,
    title: 'Welcome to Your To-Do List! ✅',
    content: 'This is your task management hub. Keep track of action items from your Linking Strategies and personal tasks. Let\'s take a quick look around!',
    position: 'center',
    spotlightPadding: 0,
  },
  {
    id: 'stats',
    target: '[data-tour="todo-stats"]',
    title: 'Task Overview',
    content: 'See your progress at a glance! Track total tasks, active items that need attention, and completed work.',
    position: 'bottom',
    spotlightPadding: 12,
  },
  {
    id: 'new-button',
    target: '[data-tour="todo-new-button"]',
    title: 'Create Tasks & Folders',
    content: 'Click here to add new tasks or create custom folders to organize your work. Tip: Folders are also auto-created when you run a Linking Strategy!',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'folder-types',
    target: null,
    title: 'Understanding Folder Types 📁',
    content: 'You\'ll see two types of folders: Custom folders (📁 teal "Custom" badge) that you create yourself, and Linking Strategy folders (🔗 orange badge) that are auto-generated from your projects. Both work the same way!',
    position: 'center',
    spotlightPadding: 0,
  },
  {
    id: 'filters',
    target: '[data-tour="todo-filters"]',
    title: 'Filter Your Tasks',
    content: 'Quickly switch between viewing all tasks, only active ones, or completed items. Stay focused on what matters most.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'actions',
    target: '[data-tour="todo-actions"]',
    title: 'Sort & Bulk Actions',
    content: 'Sort tasks by date, priority, or name. When sorted by "Date Created", you can drag and drop tasks to reorder them! Use "Select" to bulk-complete or delete multiple tasks.',
    position: 'bottom',
    spotlightPadding: 8,
  },
  {
    id: 'sample-task',
    target: '[data-tour="todo-sample-task"]',
    title: 'Your First Task',
    content: 'Here\'s a sample task to get you started! Click on any task to edit it. Let\'s open this one to see the task editor.',
    position: 'bottom',
    spotlightPadding: 8,
    action: 'openTaskModal',
  },
  {
    id: 'task-modal',
    target: '[data-tour="task-modal"]',
    title: 'Task Editor',
    content: 'This is where you edit your tasks. You can change the task name, move it to a different folder, and set the priority level.',
    position: 'left',
    spotlightPadding: 16,
  },
  {
    id: 'task-due-date',
    target: '[data-tour="task-due-date"]',
    title: 'Due Dates & Reminders',
    content: 'Set a due date to keep yourself on track. Once you add a due date, you can also set a specific time and get reminded before it\'s due!',
    position: 'left',
    spotlightPadding: 8,
  },
  {
    id: 'editing-tips',
    target: null,
    title: 'You\'re All Set! 🎉',
    content: 'That\'s the basics! Remember: set a due date first to unlock time and reminder options. Now go create your first Linking Strategy and watch tasks auto-populate here!',
    position: 'center',
    spotlightPadding: 0,
    action: 'closeTaskModal',
  },
];